# Generated by Django 4.1.10 on 2024-04-03 18:18

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAppHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('confirm_password', models.CharField(max_length=25)),
                ('team', models.CharField(max_length=25)),
                ('specialization', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('updated_date', models.DateField()),
            ],
            options={
                'db_table': 'checklistApp_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_field', models.CharField(max_length=250)),
                ('subcategory_weightage', models.JSONField(default=dict, max_length=500)),
                ('category_wise_rating', models.JSONField(default=dict, max_length=500)),
                ('risk_rating', models.FloatField()),
                ('remarks', models.JSONField(default=list, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('checklist_id', models.IntegerField()),
                ('reviewer_id', models.IntegerField()),
                ('auditor_id', models.IntegerField()),
                ('status', models.CharField(choices=[('assigned_to_rev', 'Assigned to Reviewer'), ('assigned_to_aud', 'Assigned to Auditor'), ('submitted_to_rev', 'Submitted to Reviewer'), ('submitted_to_admin', 'Submitted to Admin'), ('inprogress', 'In Progress'), ('completed', 'Completed'), ('hold', 'Hold')], default='assigned_to_rev', max_length=25)),
                ('timeline', models.JSONField(default=list, max_length=500)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('reviewer_assigned_date', models.DateField()),
                ('auditor_assigned_date', models.DateField()),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('captcha_string', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_title', models.CharField(max_length=255, unique=True)),
                ('subcategories', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_title', models.CharField(max_length=255, unique=True)),
                ('subcategories', models.JSONField(default=list, max_length=500, unique=True)),
                ('questions', models.JSONField(default=list, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=200)),
                ('question_text', models.CharField(max_length=500)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='checklistApp.checklistdata')),
            ],
        ),
        migrations.CreateModel(
            name='AudRevMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_id', models.IntegerField()),
                ('aud_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('rev_id', 'aud_id')},
            },
        ),
        migrations.CreateModel(
            name='AppField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('app_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_fields', to='checklistApp.appdetail')),
            ],
        ),
        migrations.AddField(
            model_name='appdetail',
            name='app_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_detail', to='checklistApp.appinfo'),
        ),
        migrations.CreateModel(
            name='AnswerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=250)),
                ('question_text', models.CharField(max_length=550)),
                ('answer_text', models.CharField(max_length=250)),
                ('POCs', models.JSONField(default=list, max_length=250)),
                ('app_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='checklistApp.appdetail')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('confirm_password', models.CharField(max_length=25)),
                ('team', models.CharField(max_length=25)),
                ('specialization', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('updated_date', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
