# Generated by Django 4.1.10 on 2024-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='option_wise_count',
            field=models.JSONField(default=dict, max_length=500),
        ),
    ]
